[[main]]
none = "none"

[[main]]
name = "Anchorages"
pageRef = "anchorages"
identifier = "OR1xQMVdTI"
weight = 2

[[main]]
name = "Map"
url = "test"
identifier = "1wSQXk6JMU"
weight = 3

[[main]]
name = "Boat"
pageRef = "boat"
identifier = "hrN4Dxch0F"
weight = 9999

[[footer]]
none = "none"
