[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "Hjnpg2G7pq"
weight = 1

[[main]]
name = "Anchorages"
pageRef = "anchorages"
identifier = "OR1xQMVdTI"
weight = 2

[[main]]
name = "Map"
url = "test"
identifier = "1wSQXk6JMU"
weight = 3

[[footer]]
none = "none"
