[[main]]
none = "none"

[[main]]
name = "Anchorages"
pageRef = "anchorages"
identifier = "OR1xQMVdTI"
weight = 2

[[main]]
name = "Map"
url = "https://saillogger.com/svstar-haven"
identifier = "1wSQXk6JMU"
weight = 3

[[main]]
name = "Boat"
pageRef = "boat"
identifier = "hrN4Dxch0F"
weight = 4

[[main]]
name = "Store"
pageRef = '/store'
identifier = "1wSQ3jDJMU"
weight = 5

[[footer]]
none = "none"
